default_agent: strands_claude_getting_started
agents:
  strands_claude_getting_started:
    name: strands_claude_getting_started
    entrypoint: /Users/m.hopei/Projects/Radio/KitchenAssistant/main.py
    platform: linux/arm64
    container_runtime: docker
    aws:
      execution_role: arn:aws:iam::197757129786:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-8556fc4504
      execution_role_auto_create: false
      account: '197757129786'
      region: us-west-2
      ecr_repository: 197757129786.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-strands_claude_getting_started
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
